module.exports = {
  basePath: 'Green_Industry_Pros',
  pathMaps: [
    {
      alias: 'default',
      map: {
        lb1: 'default/lb1',
        'lb-sticky-bottom': 'default/lb1',
        rail1: 'default/rail1',
        rail2: 'default/rail1',
        'infinite-rail': 'default/rail1',
        'infinite-interstitial': 'default/rail1',
        'in-content': 'default/rail1',
        reskin: 'default/reskin',
      },
    },
    {
      alias: 'mowing-maintenance',
      map: {
        lb1: 'mowing-maintenance/lb1',
        'lb-sticky-bottom': 'mowing-maintenance/lb1',
        rail1: 'mowing-maintenance/rail1',
        rail2: 'mowing-maintenance/rail1',
        'infinite-rail': 'mowing-maintenance/rail1',
        'infinite-interstitial': 'mowing-maintenance/rail1',
        'in-content': 'mowing-maintenance/rail1',
        reskin: 'mowing-maintenance/reskin',
      },
    },
    {
      alias: 'lawn-care-renovation',
      map: {
        lb1: 'lawn-care-renovation/lb1',
        'lb-sticky-bottom': 'lawn-care-renovation/lb1',
        rail1: 'lawn-care-renovation/rail1',
        rail2: 'lawn-care-renovation/rail1',
        'infinite-rail': 'lawn-care-renovation/rail1',
        'infinite-interstitial': 'lawn-care-renovation/rail1',
        'in-content': 'lawn-care-renovation/rail1',
        reskin: 'lawn-care-renovation/reskin',
      },
    },
    {
      alias: 'design-installation',
      map: {
        lb1: 'design-installation/lb1',
        'lb-sticky-bottom': 'design-installation/lb1',
        rail1: 'design-installation/rail1',
        rail2: 'design-installation/rail1',
        'infinite-rail': 'design-installation/rail1',
        'infinite-interstitial': 'design-installation/rail1',
        'in-content': 'design-installation/rail1',
        reskin: 'design-installation/reskin',
      },
    },
    {
      alias: 'irrigation-water-management',
      map: {
        lb1: 'irrigation-water-management/lb1',
        'lb-sticky-bottom': 'irrigation-water-management/lb1',
        rail1: 'irrigation-water-management/rail1',
        rail2: 'irrigation-water-management/rail1',
        'infinite-rail': 'irrigation-water-management/rail1',
        'infinite-interstitial': 'irrigation-water-management/rail1',
        'in-content': 'irrigation-water-management/rail1',
        reskin: 'irrigation-water-management/reskin',
      },
    },
    {
      alias: 'snow-ice-management',
      map: {
        lb1: 'snow-ice-management/lb1',
        'lb-sticky-bottom': 'snow-ice-management/lb1',
        rail1: 'snow-ice-management/rail1',
        rail2: 'snow-ice-management/rail1',
        'infinite-rail': 'snow-ice-management/rail1',
        'infinite-interstitial': 'snow-ice-management/rail1',
        'in-content': 'snow-ice-management/rail1',
        reskin: 'snow-ice-management/reskin',
      },
    },
  ],
};
