module.exports = {
  basePath: 'SDCExec',
  pathMaps: [
    {
      alias: 'default',
      map: {
        lb1: 'default/lb1',
        'lb-sticky-bottom': 'default/lb1',
        rail1: 'default/rail1',
        rail2: 'default/rail1',
        'infinite-rail': 'default/rail1',
        'infinite-interstitial': 'default/rail1',
        'in-content': 'default/rail1',
        reskin: 'default/reskin',
      },
    },
    {
      alias: 'warehousing',
      map: {
        lb1: 'warehousing/lb1',
        'lb-sticky-bottom': 'warehousing/lb1',
        rail1: 'warehousing/rail1',
        rail2: 'warehousing/rail1',
        'infinite-rail': 'warehousing/rail1',
        'infinite-interstitial': 'warehousing/rail1',
        'in-content': 'warehousing/rail1',
        reskin: 'warehousing/reskin',
      },
    },
    {
      alias: 'transportation',
      map: {
        lb1: 'transportation/lb1',
        'lb-sticky-bottom': 'transportation/lb1',
        rail1: 'transportation/rail1',
        rail2: 'transportation/rail1',
        'infinite-rail': 'transportation/rail1',
        'infinite-interstitial': 'transportation/rail1',
        'in-content': 'transportation/rail1',
        reskin: 'transportation/reskin',
      },
    },
    {
      alias: 'sourcing-procurement',
      map: {
        lb1: 'sourcing-procurement/lb1',
        'lb-sticky-bottom': 'sourcing-procurement/lb1',
        rail1: 'sourcing-procurement/rail1',
        rail2: 'sourcing-procurement/rail1',
        'infinite-rail': 'sourcing-procurement/rail1',
        'infinite-interstitial': 'sourcing-procurement/rail1',
        'in-content': 'sourcing-procurement/rail1',
        reskin: 'sourcing-procurement/reskin',
      },
    },
    {
      alias: 'risk-compliance',
      map: {
        lb1: 'risk-compliance/lb1',
        'lb-sticky-bottom': 'risk-compliance/lb1',
        rail1: 'risk-compliance/rail1',
        rail2: 'risk-compliance/rail1',
        'infinite-rail': 'risk-compliance/rail1',
        'infinite-interstitial': 'risk-compliance/rail1',
        'in-content': 'risk-compliance/rail1',
        reskin: 'risk-compliance/reskin',
      },
    },
    {
      alias: 'software-technology',
      map: {
        lb1: 'software-technology/lb1',
        'lb-sticky-bottom': 'software-technology/lb1',
        rail1: 'software-technology/rail1',
        rail2: 'software-technology/rail1',
        'infinite-rail': 'software-technology/rail1',
        'infinite-interstitial': 'software-technology/rail1',
        'in-content': 'software-technology/rail1',
        reskin: 'software-technology/reskin',
      },
    },
    {
      alias: 'sustainability',
      map: {
        lb1: 'sustainability/lb1',
        'lb-sticky-bottom': 'sustainability/lb1',
        rail1: 'sustainability/rail1',
        rail2: 'sustainability/rail1',
        'infinite-rail': 'sustainability/rail1',
        'infinite-interstitial': 'sustainability/rail1',
        'in-content': 'sustainability/rail1',
        reskin: 'sustainability/reskin',
      },
    },
    {
      alias: '3pl-4pl',
      map: {
        lb1: '3pl-4pl/lb1',
        'lb-sticky-bottom': '3pl-4pl/lb1',
        rail1: '3pl-4pl/rail1',
        rail2: '3pl-4pl/rail1',
        'infinite-rail': '3pl-4pl/rail1',
        'infinite-interstitial': '3pl-4pl/rail1',
        'in-content': '3pl-4pl/rail1',
        reskin: '3pl-4pl/reskin',
      },
    },
    {
      alias: 'professional-development',
      map: {
        lb1: 'professional-development/lb1',
        'lb-sticky-bottom': 'professional-development/lb1',
        rail1: 'professional-development/rail1',
        rail2: 'professional-development/rail1',
        'infinite-rail': 'professional-development/rail1',
        'infinite-interstitial': 'professional-development/rail1',
        'in-content': 'professional-development/rail1',
        reskin: 'professional-development/reskin',
      },
    },
  ],
};
