module.exports = {
  basePath: 'dmnews',
  pathMaps: [
    {
      alias: 'default',
      map: {
        lb1: 'default/lb1',
        'lb-sticky-bottom': 'default/lb1',
        rail1: 'default/rail1',
        rail2: 'default/rail1',
        'infinite-rail': 'default/rail1',
        'infinite-interstitial': 'default/rail1',
        'in-content': 'default/rail1',
        reskin: 'default/reskin',
      },
    },
    {
      alias: 'agencies',
      map: {
        lb1: 'agencies/lb1',
        'lb-sticky-bottom': 'agencies/lb1',
        rail1: 'agencies/rail1',
        rail2: 'agencies/rail1',
        'infinite-rail': 'agencies/rail1',
        'infinite-interstitial': 'agencies/rail1',
        'in-content': 'agencies/rail1',
        reskin: 'agencies/reskin',
      },
    },
    {
      alias: 'marketing-channels',
      map: {
        lb1: 'marketing-channels/lb1',
        'lb-sticky-bottom': 'marketing-channels/lb1',
        rail1: 'marketing-channels/rail1',
        rail2: 'marketing-channels/rail1',
        'infinite-rail': 'marketing-channels/rail1',
        'infinite-interstitial': 'marketing-channels/rail1',
        'in-content': 'marketing-channels/rail1',
        reskin: 'marketing-channels/reskin',
      },
    },
    {
      alias: 'content-marketing',
      map: {
        lb1: 'content-marketing/lb1',
        'lb-sticky-bottom': 'content-marketing/lb1',
        rail1: 'content-marketing/rail1',
        rail2: 'content-marketing/rail1',
        'infinite-rail': 'content-marketing/rail1',
        'infinite-interstitial': 'content-marketing/rail1',
        'in-content': 'content-marketing/rail1',
        reskin: 'content-marketing/reskin',
      },
    },
    {
      alias: 'customer-experience',
      map: {
        lb1: 'customer-experience/lb1',
        'lb-sticky-bottom': 'customer-experience/lb1',
        rail1: 'customer-experience/rail1',
        rail2: 'customer-experience/rail1',
        'infinite-rail': 'customer-experience/rail1',
        'infinite-interstitial': 'customer-experience/rail1',
        'in-content': 'customer-experience/rail1',
        reskin: 'customer-experience/reskin',
      },
    },
    {
      alias: 'data',
      map: {
        lb1: 'data/lb1',
        'lb-sticky-bottom': 'data/lb1',
        rail1: 'data/rail1',
        rail2: 'data/rail1',
        'infinite-rail': 'data/rail1',
        'infinite-interstitial': 'data/rail1',
        'in-content': 'data/rail1',
        reskin: 'data/reskin',
      },
    },
    {
      alias: 'retail',
      map: {
        lb1: 'retail/lb1',
        'lb-sticky-bottom': 'retail/lb1',
        rail1: 'retail/rail1',
        rail2: 'retail/rail1',
        'infinite-rail': 'retail/rail1',
        'infinite-interstitial': 'retail/rail1',
        'in-content': 'retail/rail1',
        reskin: 'retail/reskin',
      },
    },
  ],
};
