module.exports = [
  {
    id: 54289,
    name: 'Asphalt',
    href: '/asphalt',
    values: [{
      id: 54290,
      name: 'Additives',
      href: '/asphalt/additives',
    },
    {
      id: 54291,
      name: 'Asphalt Cleaning Equipment',
      href: '/asphalt/cleaning-equipment',
    },
    {
      id: 54292,
      name: 'Asphalt Pavers',
      href: '/asphalt/pavers',
    },
    {
      id: 54293,
      name: 'Asphalt Plants',
      href: '/asphalt/plants',
    },
    {
      id: 54294,
      name: 'Asphalt Recycling',
      href: '/asphalt/recycling',
    },
    {
      id: 54295,
      name: 'Asphalt Tack Distributors',
      href: '/asphalt/track-distributors',
    },
    {
      id: 54296,
      name: 'Asphalt Test Equipment',
      href: '/asphalt/test-equipment',
    },
    {
      id: 54297,
      name: 'Automation Systems',
      href: '/asphalt/automation-systems',
    },
    {
      id: 54298,
      name: 'Material Transfer Vehicles',
      href: '/asphalt/material-transfer-vehicles',
    },
    {
      id: 54299,
      name: 'Plant Components',
      href: '/asphalt/plant-components',
    },
    ],
  },
  {
    id: 54331,
    name: 'Attachments',
    href: '/equipment/attachments',
    values: [{
      id: 54332,
      name: 'Asphalt Cutters',
      href: '/equipment/attachments/asphalt-cutters',
    },
    {
      id: 54333,
      name: 'Attachments - Other',
      href: '/equipment/attachments/attachments-other',
    },
    {
      id: 54334,
      name: 'Augers',
      href: '/equipment/attachments/augers',
    },
    {
      id: 54335,
      name: 'Backhoe Attachments',
      href: '/equipment/attachments/backhoe-attachments',
    },
    {
      id: 54336,
      name: 'Dozer & Blade Attachments',
      href: '/equipment/attachments/dozer-blade-attachments',
    },
    {
      id: 54337,
      name: 'Brush Cutters',
      href: '/equipment/attachments/brush-cutters',
    },
    {
      id: 54338,
      name: 'Bucket Thumbs',
      href: '/equipment/attachments/bucket-thumbs',
    },
    {
      id: 54339,
      name: 'Buckets',
      href: '/equipment/attachments/buckets',
    },
    {
      id: 54340,
      name: 'Cold Planers',
      href: '/equipment/attachments/cold-planers',
    },
    {
      id: 54341,
      name: 'Compaction',
      href: '/equipment/attachments/compaction',
    },
    {
      id: 54342,
      name: 'Concrete Crushers & Shears',
      href: '/equipment/attachments/concrete-crushers-shears',
    },
    {
      id: 54343,
      name: 'Couplers',
      href: '/equipment/attachments/couplers',
    },
    {
      id: 54344,
      name: 'Forks',
      href: '/equipment/attachments/forks',
    },
    {
      id: 54345,
      name: 'Grapples',
      href: '/equipment/attachments/grapples',
    },
    {
      id: 54346,
      name: 'Hammers/Breakers',
      href: '/equipment/attachments/hammers-breakers',
    },
    {
      id: 54347,
      name: 'Landscaping Attachments',
      href: '/equipment/attachments/landscaping-attachments',
    },
    {
      id: 54348,
      name: 'Lifting & Material Handling',
      href: '/equipment/attachments/lifting-material-handling',
    },
    {
      id: 54349,
      name: 'Material Spreaders',
      href: '/equipment/attachments/material-spreaders',
    },
    {
      id: 54350,
      name: 'Sweeping Attachments',
      href: '/equipment/attachments/sweeping-attachments',
    },
    {
      id: 54351,
      name: 'Track Systems',
      href: '/equipment/attachments/track-systems',
    },
    {
      id: 54352,
      name: 'Trenching Attachments',
      href: '/equipment/attachments/trenching-attachments',
    },
    ],
  },
  {
    id: 54301,
    name: 'Business Services',
    href: '/business/business-services',
    values: [{
      id: 54302,
      name: 'Coaching & Consulting',
      href: '/business/business-services/coaching-consulting',
    },
    {
      id: 54303,
      name: 'Dealers, Service Centers',
      href: '/business/business-services/dealers-service-centers',
    },
    {
      id: 54304,
      name: 'Financing, Insurance & Leasing',
      href: '/business/business-services/financing-insurance-leasing',
    },
    {
      id: 54305,
      name: 'Rental Business Services',
      href: '/business/business-services/rental',
    },
    {
      id: 54306,
      name: 'Training & Education',
      href: '/business/business-services/training-education',
    },
    ],
  },
  {
    id: 54353,
    name: 'Compaction Equipment',
    href: '/equipment/compaction',
    values: [{
      id: 54354,
      name: 'Plate Compactors',
      href: '/equipment/compaction/plate-compactors',
    },
    {
      id: 54355,
      name: 'Pneumatic Rollers',
      href: '/equipment/compaction/pneumatic-rollers',
    },
    {
      id: 54356,
      name: 'Rammers/Tampers',
      href: '/equipment/compaction/rammers-tampers',
    },
    {
      id: 54357,
      name: 'Single-Drum Rollers',
      href: '/equipment/compaction/single-drum-rollers',
    },
    {
      id: 54358,
      name: 'Tandem Rollers',
      href: '/equipment/compaction/tandem-rollers',
    },
    {
      id: 54359,
      name: 'Trench Rollers',
      href: '/equipment/compaction/trench-rollers',
    },
    {
      id: 54360,
      name: 'Walk-Behind Compaction',
      href: '/equipment/compaction/walk-behind-compaction',
    },
    ],
  },
  {
    id: 54437,
    name: 'Concrete Equipment & Products',
    href: '/concrete/equipment-products',
    values: [{
      id: 54438,
      name: 'Concrete Drills',
      href: '/concrete/equipment-products/concrete-drills',
    },
    {
      id: 54439,
      name: 'Buggies, Conveyors & Misc.Placing',
      href: '/concrete/equipment-products/buggies-conveyors-misc-placing',
    },
    {
      id: 54440,
      name: 'Concrete Accessories',
      href: '/concrete/equipment-products/concrete-accessories',
    },
    {
      id: 54441,
      name: 'Concrete Anchoring',
      href: '/concrete/equipment-products/concrete-anchoring',
    },
    {
      id: 54442,
      name: 'Concrete Hand Tools',
      href: '/concrete/equipment-products/concrete-hand-tools',
    },
    {
      id: 54443,
      name: 'Concrete Materials',
      href: '/concrete/equipment-products/concrete-materials',
    },
    {
      id: 54444,
      name: 'Concrete Mixers',
      href: '/concrete/equipment-products/concrete-mixers',
    },
    {
      id: 54445,
      name: 'Concrete Pavers',
      href: '/concrete/equipment-products/concrete-pavers',
    },
    {
      id: 54446,
      name: 'Concrete Plants',
      href: '/concrete/equipment-products/concrete-plants',
    },
    {
      id: 54447,
      name: 'Concrete Pumps',
      href: '/concrete/equipment-products/concrete-pumps',
    },
    {
      id: 54448,
      name: 'Curbers',
      href: '/concrete/equipment-products/curbers',
    },
    {
      id: 54449,
      name: 'Flatwork Accessories',
      href: '/concrete/equipment-products/flatwork-accessories',
    },
    {
      id: 54450,
      name: 'Forms',
      href: '/concrete/equipment-products/forms',
    },
    {
      id: 54451,
      name: 'Power Trowels',
      href: '/concrete/equipment-products/power-trowels',
    },
    {
      id: 54452,
      name: 'Rebar Accessories & Equipment',
      href: '/concrete/equipment-products/rebar-accessories-equipment',
    },
    {
      id: 54453,
      name: 'Repair & Rehabilitation Products',
      href: '/concrete/equipment-products/repair-rehabilitation-products',
    },
    {
      id: 54454,
      name: 'Screeds',
      href: '/concrete/equipment-products/screeds',
    },
    {
      id: 54455,
      name: 'Surface Prep',
      href: '/concrete/equipment-products/surface-prep',
    },
    {
      id: 54456,
      name: 'Technology & Services',
      href: '/concrete/equipment-products/technology-services',
    },
    {
      id: 54457,
      name: 'Vibrating Equipment',
      href: '/concrete/equipment-products/vibrating-equipment',
    },
    {
      id: 54458,
      name: 'Waterproofing',
      href: '/concrete/equipment-products/waterproofing',
    },
    ],
  },
  {
    id: 54307,
    name: 'Construction Safety',
    href: '/business/construction-safety',
    values: [{
      id: 54308,
      name: 'Arrowboards',
      href: '/business/construction-safety/arrowboards',
    },
    {
      id: 54309,
      name: 'Barricades, Cones',
      href: '/business/construction-safety/barricades-cones',
    },
    {
      id: 54310,
      name: 'Communications Equipment',
      href: '/business/construction-safety/communications-equipment',
    },
    {
      id: 54311,
      name: 'Detectable Warnings',
      href: '/business/construction-safety/detectable-warnings',
    },
    {
      id: 54312,
      name: 'Fall Protection',
      href: '/business/construction-safety/fall-protection',
    },
    {
      id: 54313,
      name: 'Lighting, Alarms',
      href: '/business/construction-safety/lighting-alarms',
    },
    {
      id: 54314,
      name: 'Parking Stops & Speed Bumps',
      href: '/business/construction-safety/parking-stops-speed-bumps',
    },
    {
      id: 54315,
      name: 'Personal Protection Equipment',
      href: '/business/construction-safety/ppe',
    },
    {
      id: 54316,
      name: 'Safety Equipment - Other',
      href: '/business/construction-safety/safety-equipment-other',
    },
    {
      id: 54317,
      name: 'Trench Shoring & Shielding',
      href: '/business/construction-safety/trench-shoring-shielding',
    },
    {
      id: 54318,
      name: 'Ventilation',
      href: '/business/construction-safety/ventilation',
    },
    ],
  },
  {
    id: 54319,
    name: 'Construction Technology',
    href: '/construction-technology',
    values: [{
      id: 54320,
      name: 'Apps',
      href: '/construction-technology/apps',
    },
    {
      id: 54321,
      name: 'Equipment Monitoring & Logistics',
      href: '/construction-technology/equipment-monitoring-logistics',
    },
    {
      id: 54322,
      name: 'Estimating & Bidding',
      href: '/construction-technology/estimating-bidding',
    },
    {
      id: 54323,
      name: 'Personnel Management',
      href: '/construction-technology/personnel-management',
    },
    {
      id: 54324,
      name: 'Project Management',
      href: '/construction-technology/project-management',
    },
    {
      id: 54325,
      name: 'Site Layout',
      href: '/construction-technology/site-layout',
    },
    {
      id: 54326,
      name: 'Theft Prevention',
      href: '/construction-technology/theft-prevention',
    },
    {
      id: 54327,
      name: 'Machine Grade Control, GPS, Laser & Other',
      href: '/construction-technology/machine-grade-control-gps-laser-other',
    },
    {
      id: 54328,
      name: 'Surveying & Layout',
      href: '/construction-technology/surveying-layout',
    },
    {
      id: 54329,
      name: 'Construction Safety Technology',
      href: '/construction-technology/construction-safety-technology',
    },
    ],
  },
  {
    id: 54459,
    name: 'Decorative Concrete',
    href: '/concrete/decorative',
    values: [{
      id: 54460,
      name: 'Coatings & Sealants',
      href: '/concrete/decorative/coatings-sealants',
    },
    {
      id: 54461,
      name: 'Colors & Stains',
      href: '/concrete/decorative/colors-stains',
    },
    {
      id: 54462,
      name: 'Concrete Countertops',
      href: '/concrete/decorative/concrete-countertops',
    },
    {
      id: 54463,
      name: 'Concrete Molds',
      href: '/concrete/decorative/concrete-molds',
    },
    {
      id: 54464,
      name: 'Decorative Overlays',
      href: '/concrete/decorative/decorative-overlays',
    },
    {
      id: 54465,
      name: 'Educational Resources',
      href: '/concrete/decorative/educational-resources',
    },
    {
      id: 54466,
      name: 'Polishing Materials & Equipment',
      href: '/concrete/decorative/polishing-materials-equipment',
    },
    {
      id: 54467,
      name: 'Stencils & Stamps',
      href: '/concrete/decorative/stencils-stamps',
    },
    ],
  },
  {
    id: 54361,
    name: 'Earthmoving - Compact',
    href: '/equipment/earthmoving-compact',
    values: [{
      id: 54362,
      name: 'Compact Track Loaders',
      href: '/equipment/earthmoving-compact/track-loaders',
    },
    {
      id: 54363,
      name: 'Compact Tractors',
      href: '/equipment/earthmoving-compact/tractors',
    },
    {
      id: 54364,
      name: 'Compact Wheel Loaders',
      href: '/equipment/earthmoving-compact/wheel-loaders',
    },
    {
      id: 54365,
      name: 'Mini Excavators',
      href: '/equipment/earthmoving-compact/mini-excavators',
    },
    {
      id: 54366,
      name: 'Mini Skid Steer, Track Loaders',
      href: '/equipment/earthmoving-compact/mini-skid-steer-track-loaders',
    },
    {
      id: 54367,
      name: 'Skid Steers',
      href: '/equipment/earthmoving-compact/skid-steers',
    },
    {
      id: 54368,
      name: 'Tractor Loader Backhoes',
      href: '/equipment/earthmoving-compact/tractor-loader-backhoes',
    },
    ],
  },
  {
    id: 54369,
    name: 'Earthmoving Equipment',
    href: '/equipment/earthmoving',
    values: [{
      id: 54370,
      name: 'Towed Scrapers',
      href: '/equipment/earthmoving/towed-scrapers',
    },
    {
      id: 54371,
      name: 'Articulated, Rigid Dump Trucks',
      href: '/equipment/earthmoving/articulated-rigid-dump-trucks',
    },
    {
      id: 54372,
      name: 'Backhoe Loaders',
      href: '/equipment/earthmoving/backhoe-loaders',
    },
    {
      id: 54373,
      name: 'Dozers',
      href: '/equipment/earthmoving/dozers',
    },
    {
      id: 54374,
      name: 'Excavators',
      href: '/equipment/earthmoving/excavators',
    },
    {
      id: 54375,
      name: 'Graders, Scrapers',
      href: '/equipment/earthmoving/graders-scrapers',
    },
    {
      id: 54376,
      name: 'Loaders',
      href: '/equipment/earthmoving/loaders',
    },
    {
      id: 54377,
      name: 'Site Dumpers',
      href: '/equipment/earthmoving/site-dumpers',
    },
    {
      id: 54378,
      name: 'Soil Stabilization Equipment',
      href: '/equipment/earthmoving/soil-stabilization',
    },
    ],
  },
  {
    id: 54379,
    name: 'Fleet Maintenance',
    href: '/equipment/fleet-maintenance',
    values: [{
      id: 54380,
      name: 'Batteries',
      href: '/equipment/fleet-maintenance/batteries',
    },
    {
      id: 54381,
      name: 'Coolants',
      href: '/equipment/fleet-maintenance/coolants',
    },
    {
      id: 54382,
      name: 'Filters',
      href: '/equipment/fleet-maintenance/filters',
    },
    {
      id: 54383,
      name: 'Lubricating Equipment',
      href: '/equipment/fleet-maintenance/lubricating',
    },
    {
      id: 54384,
      name: 'Oil Analysis',
      href: '/equipment/fleet-maintenance/oil-analysis',
    },
    {
      id: 54385,
      name: 'Oils, Lubricants & Greases',
      href: '/equipment/fleet-maintenance/oils-lubricants-greases',
    },
    {
      id: 54386,
      name: 'Belts, Hoses & Fittings',
      href: '/equipment/fleet-maintenance/belts-hoses-fittings',
    },
    {
      id: 54387,
      name: 'Diesel Engines',
      href: '/equipment/fleet-maintenance/diesel-engines',
    },
    {
      id: 54388,
      name: 'Gasoline Engines',
      href: '/equipment/fleet-maintenance/gasoline-engines',
    },
    {
      id: 54389,
      name: 'Ground Engaging Tools',
      href: '/equipment/fleet-maintenance/ground-engaging-tools',
    },
    {
      id: 54390,
      name: 'Hydraulic System Components',
      href: '/equipment/fleet-maintenance/hydraulic-system-components',
    },
    {
      id: 54391,
      name: 'Other Components',
      href: '/equipment/fleet-maintenance/other-components',
    },
    {
      id: 54392,
      name: 'Replacement Parts',
      href: '/equipment/fleet-maintenance/replacement-parts',
    },
    {
      id: 54393,
      name: 'Tires',
      href: '/equipment/fleet-maintenance/tires',
    },
    {
      id: 54394,
      name: 'Undercarriage',
      href: '/equipment/fleet-maintenance/undercarriage',
    },
    {
      id: 54395,
      name: 'Service Tools',
      href: '/equipment/fleet-maintenance/service-tools',
    },
    {
      id: 54396,
      name: 'Shop Products',
      href: '/equipment/fleet-maintenance/shop-products',
    },
    ],
  },
  {
    id: 54498,
    name: 'Lifting Equipment',
    href: '/rental/lifting-equipment',
    values: [{
      id: 54499,
      name: 'Boom Lift',
      href: '/rental/lifting-equipment/boom-lift',
    },
    {
      id: 54500,
      name: 'Boom Truck',
      href: '/rental/lifting-equipment/boom-truck',
    },
    {
      id: 54501,
      name: 'Crane',
      href: '/rental/lifting-equipment/crane',
    },
    {
      id: 54502,
      name: 'Hoists',
      href: '/rental/lifting-equipment/hoists',
    },
    {
      id: 54503,
      name: 'Industrial Forklift',
      href: '/rental/lifting-equipment/industrial-forklift',
    },
    {
      id: 54504,
      name: 'Rough Terrain Forklift',
      href: '/rental/lifting-equipment/rough-terrain-forklift',
    },
    {
      id: 54505,
      name: 'Scaffolding',
      href: '/rental/lifting-equipment/scaffolding',
    },
    {
      id: 54506,
      name: 'Scissor Lift',
      href: '/rental/lifting-equipment/scissor-lift',
    },
    {
      id: 54507,
      name: 'Telescopic Handler',
      href: '/rental/lifting-equipment/telescopic-handler',
    },
    {
      id: 54508,
      name: 'Vertical Lift',
      href: '/rental/lifting-equipment/vertical-lift',
    },
    {
      id: 54509,
      name: 'Winch',
      href: '/rental/lifting-equipment/winch',
    },
    ],
  },
  {
    id: 54397,
    name: 'Material Processing & Debris Handling',
    href: '/equipment/material-processing-debris-handling',
    values: [{
      id: 54398,
      name: 'Chippers',
      href: '/equipment/material-processing-debris-handling/chippers',
    },
    {
      id: 54399,
      name: 'Conveyors',
      href: '/equipment/material-processing-debris-handling/conveyors',
    },
    {
      id: 54400,
      name: 'Crushing & Screening Plants',
      href: '/equipment/material-processing-debris-handling/crushing-screening-plants',
    },
    {
      id: 54401,
      name: 'Grinders & Shredders',
      href: '/equipment/material-processing-debris-handling/grinders-shredders',
    },
    {
      id: 54402,
      name: 'Land Clearing',
      href: '/equipment/material-processing-debris-handling/land-clearing',
    },
    {
      id: 54403,
      name: 'Mobile Mulchers',
      href: '/equipment/material-processing-debris-handling/mobile-mulchers',
    },
    ],
  },
  {
    id: 54469,
    name: 'Pavement Marking & Striping',
    href: '/pavement-maintenance/marking-striping',
    values: [{
      id: 54470,
      name: 'Beads & Bead Dispensers',
      href: '/pavement-maintenance/marking-striping/beads-bead-dispensers',
    },
    {
      id: 54471,
      name: 'Marking Removal',
      href: '/pavement-maintenance/marking-striping/marking-removal',
    },
    {
      id: 54472,
      name: 'Paint & Thermoplastic Materials',
      href: '/pavement-maintenance/marking-striping/paint-thermoplastic-materials',
    },
    {
      id: 54473,
      name: 'Pavement Stencils',
      href: '/pavement-maintenance/marking-striping/pavement-stencils',
    },
    {
      id: 54474,
      name: 'Reflective Markers',
      href: '/pavement-maintenance/marking-striping/reflective-markers',
    },
    {
      id: 54475,
      name: 'Reflectivity Measuring Devices',
      href: '/pavement-maintenance/marking-striping/reflectivity-measuring-devices',
    },
    {
      id: 54476,
      name: 'Skid- & Truck-Mounted Stripers',
      href: '/pavement-maintenance/marking-striping/skid-truck-mounted-stripers',
    },
    {
      id: 54477,
      name: 'Thermoplastic Application Equipment',
      href: '/pavement-maintenance/marking-striping/thermoplastic-application-equipment',
    },
    {
      id: 54478,
      name: 'Thermoplastic Melters',
      href: '/pavement-maintenance/marking-striping/thermoplastic-melters',
    },
    {
      id: 54479,
      name: 'Walk-Behind Stripers',
      href: '/pavement-maintenance/marking-striping/walk-behind-stripers',
    },
    ],
  },
  {
    id: 54480,
    name: 'Pavement Preservation & Maintenance',
    href: '/pavement-maintenance/preservation-maintenance',
    values: [{
      id: 54481,
      name: 'Chip Seal Equipment & Materials',
      href: '/pavement-maintenance/preservation-maintenance/chip-seal-equipment-materials',
    },
    {
      id: 54482,
      name: 'Cracksealing Equipment & Materials',
      href: '/pavement-maintenance/preservation-maintenance/cracksealing-equipment-materials',
    },
    {
      id: 54483,
      name: 'Geotextiles & Paving Fabrics',
      href: '/pavement-maintenance/preservation-maintenance/geotextiles-paving-fabrics',
    },
    {
      id: 54484,
      name: 'Infrared Repair Machines',
      href: '/pavement-maintenance/preservation-maintenance/infrared-repair-machines',
    },
    {
      id: 54485,
      name: 'Microsurfacing Equipment & Materials',
      href: '/pavement-maintenance/preservation-maintenance/microsurfacing-equipment-materials',
    },
    {
      id: 54486,
      name: 'Patching Equipment & Materials',
      href: '/pavement-maintenance/preservation-maintenance/patching-equipment-materials',
    },
    {
      id: 54487,
      name: 'Paving & Pavement Maintenance Tools',
      href: '/pavement-maintenance/preservation-maintenance/paving-pavement-maintenance-tools',
    },
    {
      id: 54488,
      name: 'Planers & Milling Machines',
      href: '/pavement-maintenance/preservation-maintenance/planers-milling-machines',
    },
    {
      id: 54489,
      name: 'Sealcoating Equipment & Materials',
      href: '/pavement-maintenance/preservation-maintenance/sealcoating-equipment-materials',
    },
    {
      id: 54490,
      name: 'Slurry Seal Equipment & Materials',
      href: '/pavement-maintenance/preservation-maintenance/slurry-seal-equipment-materials',
    },
    ],
  },
  {
    id: 54510,
    name: 'Rental Inventory',
    href: '/rental/inventory',
    values: [{
      id: 54511,
      name: 'Aerators',
      href: '/rental/inventory/aerators',
    },
    {
      id: 54512,
      name: 'Blowers',
      href: '/rental/inventory/blowers',
    },
    {
      id: 54513,
      name: 'Carpet Cleaners',
      href: '/rental/inventory/carpet-cleaners',
    },
    {
      id: 54514,
      name: 'Cleaners',
      href: '/rental/inventory/cleaners',
    },
    {
      id: 54515,
      name: 'Drain Cleaners',
      href: '/rental/inventory/drain-cleaners',
    },
    {
      id: 54516,
      name: 'Earth Augers (handheld)',
      href: '/rental/inventory/handheld-earth-augers',
    },
    {
      id: 54517,
      name: 'Edgers',
      href: '/rental/inventory/edgers',
    },
    {
      id: 54518,
      name: 'Floor Polisher',
      href: '/rental/inventory/floor-polisher',
    },
    {
      id: 54519,
      name: 'Floor Sander',
      href: '/rental/inventory/floor-sander',
    },
    {
      id: 54520,
      name: 'Floor Strippers',
      href: '/rental/inventory/floor-strippers',
    },
    {
      id: 54521,
      name: 'Lawn & Garden Equipment Parts',
      href: '/rental/inventory/lawn-garden-equipment-parts',
    },
    {
      id: 54522,
      name: 'Log Splitters',
      href: '/rental/inventory/log-splitters',
    },
    {
      id: 54523,
      name: 'Mowers',
      href: '/rental/inventory/mowers',
    },
    {
      id: 54524,
      name: 'Outdoor Vacs',
      href: '/rental/inventory/outdoor-vacuums',
    },
    {
      id: 54525,
      name: 'Pressure Washers',
      href: '/rental/inventory/pressure-washers',
    },
    {
      id: 54526,
      name: 'Rototillers',
      href: '/rental/inventory/rototillers',
    },
    {
      id: 54527,
      name: 'Stump Grinders',
      href: '/rental/inventory/stump-grinders',
    },
    {
      id: 54528,
      name: 'Trimmers',
      href: '/rental/inventory/trimmers',
    },
    {
      id: 54529,
      name: 'Vacuums',
      href: '/rental/inventory/vaccums',
    },
    ],
  },
  {
    id: 54404,
    name: 'Snow Removal Equipment',
    href: '/equipment/snow-removal-equipment',
  },
  {
    id: 54491,
    name: 'Sweepers',
    href: '/pavement-maintenance/sweepers',
    values: [{
      id: 54492,
      name: 'Magnetic Sweepers',
      href: '/pavement-maintenance/sweepers/magnetic',
    },
    {
      id: 54493,
      name: 'Mechanical Sweepers',
      href: '/pavement-maintenance/sweepers/mechanical',
    },
    {
      id: 54494,
      name: 'Regenerative Sweepers',
      href: '/pavement-maintenance/sweepers/regenerative',
    },
    {
      id: 54495,
      name: 'Replacement Brooms & Brushes',
      href: '/pavement-maintenance/sweepers/replacement-brooms-brushes',
    },
    {
      id: 54496,
      name: 'Vacuum Sweepers',
      href: '/pavement-maintenance/sweepers/vacuum',
    },
    ],
  },
  {
    id: 54531,
    name: 'Trucks & Accessories',
    href: '/trucks/trucks-accessories',
    values: [{
      id: 54532,
      name: 'Utility Vehicles',
      href: '/trucks/trucks-accessories/utility-vehicles',
    },
    {
      id: 54533,
      name: 'Dump Bodies & Bed Inserts',
      href: '/trucks/trucks-accessories/dump-bodies-bed-inserts',
    },
    {
      id: 54534,
      name: 'Dump Trailers',
      href: '/trucks/trucks-accessories/dump-trailers',
    },
    {
      id: 54535,
      name: 'Equipment Trailers',
      href: '/trucks/trucks-accessories/equipment-trailers',
    },
    {
      id: 54536,
      name: 'Heavy Trucks: Class 7 & 8',
      href: '/trucks/trucks-accessories/heavy-trucks-class-7-8',
    },
    {
      id: 54537,
      name: 'Medium Duty Trucks: Class 4 - 6',
      href: '/trucks/trucks-accessories/medium-duty-trucks-class-4-6',
    },
    {
      id: 54538,
      name: 'Onboard Power Sources',
      href: '/trucks/trucks-accessories/onboard-power-sources',
    },
    {
      id: 54539,
      name: 'Pickup Trucks & Vans',
      href: '/trucks/trucks-accessories/pickup-trucks-vans',
    },
    {
      id: 54540,
      name: 'Safety & Security Equipment',
      href: '/trucks/trucks-accessories/safety-security-equipment',
    },
    {
      id: 54541,
      name: 'Service & Fuel Trucks',
      href: '/trucks/trucks-accessories/service-fuel-trucks',
    },
    {
      id: 54542,
      name: 'Tarps & Racks',
      href: '/trucks/trucks-accessories/tarps-racks',
    },
    {
      id: 54543,
      name: 'Trailer Accessories',
      href: '/trucks/trucks-accessories/trailer-accessories',
    },
    {
      id: 54544,
      name: 'Truck Accessories',
      href: '/trucks/trucks-accessories/truck-accessories',
    },
    {
      id: 54545,
      name: 'Truck Parts & Components',
      href: '/trucks/trucks-accessories/truck-parts-components',
    },
    ],
  },
  {
    id: 54405,
    name: 'Underground Equipment',
    href: '/equipment/underground',
    values: [{
      id: 54406,
      name: 'Bits & Accessories',
      href: '/equipment/underground/bits-accessories',
    },
    {
      id: 54407,
      name: 'Directional Drilling Equipment',
      href: '/equipment/underground/directional-drilling-equipment',
    },
    {
      id: 54408,
      name: 'Vertical Drilling Equipment',
      href: '/equipment/underground/vertical-drilling-equipment',
    },
    {
      id: 54409,
      name: 'Horizontal Bursting, Boring & Piercing',
      href: '/equipment/underground/horizontal-bursting-boring-piercing',
    },
    {
      id: 54410,
      name: 'Trenchers',
      href: '/equipment/underground/trenchers',
    },
    {
      id: 54411,
      name: 'Utility Locators',
      href: '/equipment/underground/utility-locators',
    },
    {
      id: 54412,
      name: 'Vacuum Excavation Equipment',
      href: '/equipment/underground/vacuum-excavation-equipment',
    },
    {
      id: 54413,
      name: 'Walk-Behind Trenchers',
      href: '/equipment/underground/walk-behind-trenchers',
    },
    ],
  },
  {
    id: 54414,
    name: 'Worksite Equipment',
    href: '/equipment/worksite',
    values: [{
      id: 54415,
      name: 'Abrasives',
      href: '/equipment/worksite/abrasives',
    },
    {
      id: 54416,
      name: 'Air Tools & Accessories',
      href: '/equipment/worksite/air-tools-accessories',
    },
    {
      id: 54417,
      name: 'Portable Compressors (Under 85 Cfm)',
      href: '/equipment/worksite/portal-compressors',
    },
    {
      id: 54418,
      name: 'Towable Compressors (85 Cfm and larger)',
      href: '/equipment/worksite/towable-compressors',
    },
    {
      id: 54419,
      name: 'Electric Tools & Accessories',
      href: '/equipment/worksite/electric-tools-accessories',
    },
    {
      id: 54420,
      name: 'Engine-Powered Tools & Accessories',
      href: '/equipment/worksite/engine-powered-tools-accessories',
    },
    {
      id: 54421,
      name: 'Ground Heaters',
      href: '/equipment/worksite/ground-heaters',
    },
    {
      id: 54422,
      name: 'Hydraulic Tools & Accessories',
      href: '/equipment/worksite/hydraulic-tools-accessories',
    },
    {
      id: 54423,
      name: 'Misc. Hand Tools',
      href: '/equipment/worksite/misc-hand-tools',
    },
    {
      id: 54424,
      name: 'Paint & Painting Equipment',
      href: '/equipment/worksite/paint-painting-equipment',
    },
    {
      id: 54425,
      name: 'Portable Climate Control',
      href: '/equipment/worksite/portable-climate-control',
    },
    {
      id: 54426,
      name: 'Portable Generators',
      href: '/equipment/worksite/portable-generators',
    },
    {
      id: 54427,
      name: 'Portable Lighting',
      href: '/equipment/worksite/portable-lighting',
    },
    {
      id: 54428,
      name: 'Pumps',
      href: '/equipment/worksite/pumps',
    },
    {
      id: 54429,
      name: 'Saw Blades & Chain',
      href: '/equipment/worksite/saw-blades-chain',
    },
    {
      id: 54430,
      name: 'Concrete Chain Saws',
      href: '/equipment/worksite/concrete-chain-saws',
    },
    {
      id: 54431,
      name: 'Cutoff Saws',
      href: '/equipment/worksite/cutoff-saws',
    },
    {
      id: 54432,
      name: 'Saws - Other',
      href: '/equipment/worksite/saws-other',
    },
    {
      id: 54433,
      name: 'Walk-Behind Saws',
      href: '/equipment/worksite/walk-behind-saws',
    },
    {
      id: 54434,
      name: 'Towable Generators',
      href: '/equipment/worksite/towable-generators',
    },
    {
      id: 54435,
      name: 'Welding Equipment & Supplies',
      href: '/equipment/worksite/welding-equipment-supplies',
    },
    ],
  },
];
