module.exports = {
  basePath: 'forconstructionpros',
  pathMaps: [
    {
      alias: 'default',
      map: {
        lb1: 'default/lb1',
        'lb-sticky-bottom': 'default/lb1',
        rail1: 'default/rail1',
        rail2: 'default/rail1',
        'infinite-rail': 'default/rail1',
        'infinite-interstitial': 'default/rail1',
        'in-content': 'default/rail1',
        reskin: 'default/reskin',
      },
    },
    {
      alias: 'equipment',
      map: {
        lb1: 'equipment/lb1',
        'lb-sticky-bottom': 'equipment/lb1',
        rail1: 'equipment/rail1',
        rail2: 'equipment/rail1',
        'infinite-rail': 'equipment/rail1',
        'infinite-interstitial': 'equipment/rail1',
        'in-content': 'equipment/rail1',
        reskin: 'equipment/reskin',
      },
    },
    {
      alias: 'trucks',
      map: {
        lb1: 'trucks/lb1',
        'lb-sticky-bottom': 'trucks/lb1',
        rail1: 'trucks/rail1',
        rail2: 'trucks/rail1',
        'infinite-rail': 'trucks/rail1',
        'infinite-interstitial': 'trucks/rail1',
        'in-content': 'trucks/rail1',
        reskin: 'trucks/reskin',
      },
    },
    {
      alias: 'rental',
      map: {
        lb1: 'rental/lb1',
        'lb-sticky-bottom': 'rental/lb1',
        rail1: 'rental/rail1',
        rail2: 'rental/rail1',
        'infinite-rail': 'rental/rail1',
        'infinite-interstitial': 'rental/rail1',
        'in-content': 'rental/rail1',
        reskin: 'rental/reskin',
      },
    },
    {
      alias: 'concrete',
      map: {
        lb1: 'concrete/lb1',
        'lb-sticky-bottom': 'concrete/lb1',
        rail1: 'concrete/rail1',
        rail2: 'concrete/rail1',
        'infinite-rail': 'concrete/rail1',
        'infinite-interstitial': 'concrete/rail1',
        'in-content': 'concrete/rail1',
        reskin: 'concrete/reskin',
      },
    },
    {
      alias: 'asphalt',
      map: {
        lb1: 'asphalt/lb1',
        'lb-sticky-bottom': 'asphalt/lb1',
        rail1: 'asphalt/rail1',
        rail2: 'asphalt/rail1',
        'infinite-rail': 'asphalt/rail1',
        'infinite-interstitial': 'asphalt/rail1',
        'in-content': 'asphalt/rail1',
        reskin: 'asphalt/reskin',
      },
    },
    {
      alias: 'pavement-maintenance',
      map: {
        lb1: 'pavement-maintenance/lb1',
        'lb-sticky-bottom': 'pavement-maintenance/lb1',
        rail1: 'pavement-maintenance/rail1',
        rail2: 'pavement-maintenance/rail1',
        'infinite-rail': 'pavement-maintenance/rail1',
        'infinite-interstitial': 'pavement-maintenance/rail1',
        'in-content': 'pavement-maintenance/rail1',
        reskin: 'pavement-maintenance/reskin',
      },
    },
    {
      alias: 'equipment-management',
      map: {
        lb1: 'equipment-management/lb1',
        'lb-sticky-bottom': 'equipment-management/lb1',
        rail1: 'equipment-management/rail1',
        rail2: 'equipment-management/rail1',
        'infinite-rail': 'equipment-management/rail1',
        'infinite-interstitial': 'equipment-management/rail1',
        'in-content': 'equipment-management/rail1',
        reskin: 'equipment-management/reskin',
      },
    },
    {
      alias: 'construction-technology',
      map: {
        lb1: 'construction-technology/lb1',
        'lb-sticky-bottom': 'construction-technology/lb1',
        rail1: 'construction-technology/rail1',
        rail2: 'construction-technology/rail1',
        'infinite-rail': 'construction-technology/rail1',
        'infinite-interstitial': 'construction-technology/rail1',
        'in-content': 'construction-technology/rail1',
        reskin: 'construction-technology/reskin',
      },
    },
    {
      alias: 'business',
      map: {
        lb1: 'business/lb1',
        'lb-sticky-bottom': 'business/lb1',
        rail1: 'business/rail1',
        rail2: 'business/rail1',
        'infinite-rail': 'business/rail1',
        'infinite-interstitial': 'business/rail1',
        'in-content': 'business/rail1',
        reskin: 'business/reskin',
      },
    },
    {
      alias: 'conexpo',
      map: {
        lb1: 'conexpo/lb1',
        'lb-sticky-bottom': 'conexpo/lb1',
        rail1: 'conexpo/rail1',
        rail2: 'conexpo/rail1',
        'infinite-rail': 'conexpo/rail1',
        'infinite-interstitial': 'conexpo/rail1',
        'in-content': 'conexpo/rail1',
        reskin: 'conexpo/reskin',
      },
    },
    {
      alias: 'profit-matters',
      map: {
        lb1: 'profit-matters/lb1',
        'lb-sticky-bottom': 'profit-matters/lb1',
        rail1: 'profit-matters/rail1',
        rail2: 'profit-matters/rail1',
        'infinite-rail': 'profit-matters/rail1',
        'infinite-interstitial': 'profit-matters/rail1',
        'in-content': 'profit-matters/rail1',
        reskin: 'profit-matters/reskin',
      },
    },
  ],
};
